name: CI

on:
  push:
    branches: [ master ]
    tags:
      - 'v*.*.*'
  pull_request:
    branches: [ master ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build (Kotlin Multiplatform)
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: wrapper

      # Android target needs the SDK to be present even though this is a library.
      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Android SDK components (API 36)
        shell: bash
        run: |
          set -euo pipefail
          yes | sdkmanager --licenses > /dev/null || true
          # Do 36 or die: require API 36 and build-tools 36.0.0
          sdkmanager --install "platform-tools" "platforms;android-36" "build-tools;36.0.0"

      - name: Cache Gradle and Kotlin build caches
        uses: actions/cache@v4
        with:
          path: |
            .gradle
            .kotlin
          key: ${{ runner.os }}-project-caches-${{ hashFiles('**/*.gradle*', '**/gradle.properties', 'gradle/libs.versions.toml', 'gradle/wrapper/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-project-caches-

      - name: Build
        run: ./gradlew --no-daemon --stacktrace clean build

      - name: Upload Test Reports (always)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: test-reports
          path: |
            **/build/reports/tests/**/*
            **/build/reports/kotlin/**/*
          if-no-files-found: ignore

  release:
    name: Publish to Maven Central
    if: startsWith(github.ref, 'refs/tags/v')
    needs: build
    runs-on: macos-latest
    permissions:
      contents: read
    env:
      ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_TOKEN_USERNAME }}
      ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_TOKEN_PASSWORD }}
      ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_PRIVATE_KEY }}
      ORG_GRADLE_PROJECT_signingInMemoryKeyId: ${{ secrets.GPG_KEY_ID }}
      ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.GPG_KEY_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v4

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          gradle-version: wrapper

      - name: Publish to Maven Central
        shell: bash
        run: |
          set -euo pipefail
          ./gradlew --no-daemon --stacktrace publishToMavenCentral
